### ISSUE TITLE
我觉得可以通过审核

### ISSUE THREAD

**Issue by pantaopt** [lilidan/OCEval#3]
源码还没有细抠，逐步断点去理解。我大致的理解是解析oc语法，nsinvoke实现消息转发和aspects实现method swizling，对吗？ nsinvoke实现消息转发和aspects实现method swizling在上线审核上都没问题。
应该可以使用在线上吧？

**Comment by 1oo1** [comment]
libffi 会导致审核不通过。

**Comment by pantaopt** [comment]
> libffi 会导致审核不通过。

受教了

**Comment by Demonsword27** [comment]
> libffi 会导致审核不通过。

你试过吗？就在那一本正经胡说八道？
